// src/store/meals.js

export const mealsData = [
  {
    id: 1,
    name: "Breakfast Bowl",
    calories: 350,
    carbs: 45,
    protein: 20,
    fats: 10,
  },
  {
    id: 2,
    name: "Chicken Salad",
    calories: 300,
    carbs: 20,
    protein: 30,
    fats: 12,
  },
  {
    id: 3,
    name: "Pasta Dish",
    calories: 500,
    carbs: 60,
    protein: 15,
    fats: 20,
  },
  { id: 4, name: "Smoothie", calories: 250, carbs: 30, protein: 10, fats: 5 },
  {
    id: 5,
    name: "Grilled Fish",
    calories: 400,
    carbs: 15,
    protein: 35,
    fats: 18,
  },
  {
    id: 6,
    name: "Veggie Stir Fry",
    calories: 350,
    carbs: 40,
    protein: 12,
    fats: 8,
  },
  { id: 7, name: "Fruit Plate", calories: 200, carbs: 50, protein: 5, fats: 2 },
  {
    id: 8,
    name: "Steak and Potatoes",
    calories: 600,
    carbs: 35,
    protein: 40,
    fats: 25,
  },
  {
    id: 9,
    name: "Avocado Toast",
    calories: 300,
    carbs: 25,
    protein: 10,
    fats: 15,
  },
  { id: 10, name: "Omelette", calories: 250, carbs: 10, protein: 20, fats: 15 },
  { id: 11, name: "Tacos", calories: 400, carbs: 50, protein: 25, fats: 20 },
  { id: 12, name: "Pizza", calories: 700, carbs: 80, protein: 30, fats: 25 },
  {
    id: 13,
    name: "Caesar Salad",
    calories: 150,
    carbs: 10,
    protein: 5,
    fats: 12,
  },
  {
    id: 14,
    name: "Fruit Smoothie",
    calories: 300,
    carbs: 50,
    protein: 10,
    fats: 5,
  },
  {
    id: 15,
    name: "Burger and Fries",
    calories: 800,
    carbs: 60,
    protein: 35,
    fats: 40,
  },
];
