// src/store/meals.js

export const mealsData = [
  {
    id: 1,
    name: "Protein Breakfast Bowl",
    calories: 400,
    carbs: 40,
    protein: 30,
    fats: 15,
    image: "/images/protein-breakfast-bowl.jpg",
  },
  {
    id: 2,
    name: "Grilled Chicken Salad",
    calories: 350,
    carbs: 20,
    protein: 40,
    fats: 12,
    image: "/images/grilled-chicken-salad.jpg",
  },
  {
    id: 3,
    name: "Lean Pasta with Veggies",
    calories: 500,
    carbs: 55,
    protein: 25,
    fats: 15,
    image: "/images/lean-pasta-veg.jpg",
  },
  {
    id: 4,
    name: "Berry Protein Smoothie",
    calories: 280,
    carbs: 30,
    protein: 25,
    fats: 8,
    image: "/images/berry-smoothie.jpg",
  },
  {
    id: 5,
    name: "Grilled Salmon with Quinoa",
    calories: 450,
    carbs: 30,
    protein: 40,
    fats: 18,
    image: "/images/grilled-salmon-quinoa.jpg",
  },
  {
    id: 6,
    name: "Vegetarian Stir Fry",
    calories: 400,
    carbs: 45,
    protein: 18,
    fats: 12,
    image: "/images/veg-stir-fry.jpg",
  },
  {
    id: 7,
    name: "Fruit and Nut Protein Plate",
    calories: 350,
    carbs: 35,
    protein: 25,
    fats: 15,
    image: "/images/fruit-nut-plate.jpg",
  },
  {
    id: 8,
    name: "Beef Steak and Sweet Potatoes",
    calories: 600,
    carbs: 40,
    protein: 50,
    fats: 30,
    image: "/images/steak-sweet-potatoes.jpg",
  },
  {
    id: 9,
    name: "Avocado Toast with Egg",
    calories: 350,
    carbs: 30,
    protein: 20,
    fats: 20,
    image: "/images/avocado-toast.jpg",
  },
  {
    id: 10,
    name: "Egg White Omelette with Veggies",
    calories: 250,
    carbs: 10,
    protein: 30,
    fats: 10,
    image: "/images/egg-white-omelette.jpg",
  },
  {
    id: 11,
    name: "Turkey Tacos",
    calories: 400,
    carbs: 40,
    protein: 30,
    fats: 15,
    image: "/images/turkey-tacos.jpg",
  },
  {
    id: 12,
    name: "Chicken and Veggie Pizza",
    calories: 550,
    carbs: 50,
    protein: 40,
    fats: 20,
    image: "/images/chicken-veggie-pizza.jpg",
  },
  {
    id: 13,
    name: "Kale and Quinoa Salad",
    calories: 250,
    carbs: 30,
    protein: 12,
    fats: 10,
    image: "/images/kale-quinoa-salad.jpg",
  },
  {
    id: 14,
    name: "Green Protein Smoothie",
    calories: 350,
    carbs: 30,
    protein: 25,
    fats: 8,
    image: "/images/green-protein-smoothie.jpg",
  },
  {
    id: 15,
    name: "Bison Burger with Sweet Potatoes",
    calories: 700,
    carbs: 45,
    protein: 50,
    fats: 35,
    image: "/images/bison-burger-sweet-potatoes.jpg",
  },
];
